### ISSUE TITLE
uncompressed sharded format

### ISSUE THREAD

**Issue by tannerBMC** [seung-lab/igneous#152]
I'm using igneous version 4.15.2 and create a sharded volume from a non-sharded volume via create_image_shard_transfer_tasks. It works and I can view it via neuroglancer. Thanks a lot!

Howerver I'm unable to view it with the siibra-explorer in the current form. One issue is that they use dataproxy, which does not support compressed data. 
Using   encoding='raw',   and the undocumented parameter   compress=None,  I managed to get  "data_encoding": "raw",

However I cannot modify
"minishard_index_encoding": "gzip",
as this is not supported, i.e.
_encodingTypeError: create_image_shard_transfer_tasks() got an unexpected keyword argument 'minishard_index_encoding'

Is there a way to generate sharded files where everything is uncompressed?

**Comment by william-silversmith** [comment]
Hi @tannerBMC, I pushed an update in version 4.17.0. Would you mind giving that a try? You can now set `minishard_index_encoding="raw"`.

**Comment by tannerBMC** [comment]
Hi William

Thanks a lot for your fast response and adaption. Most appreciated.

Looks good.

I tested it and can create in this way info files which state   "minishard_index_encoding": "raw" and the chunk files increased in size by 17 bits. I can load the generated chunks into neuroglancer without problems.

Unfortunately it did not solve my problem with loading the sharded chunks into siibra-explorer (https://atlases.ebrains.eu/viewer/). They might be use an earlier version of sharded chunk file format.

Best regards,
  Christine Tanner

**Comment by william-silversmith** [comment]
Thanks for the kind words. If you get in touch with the siibra people, you
can let them know that I'd be willing to give them some advice on
supporting the sharded format. Sorry you're running into trouble!

Will
